/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ContentDto
 */
export interface ContentDto {
    /**
     * Use our pre-defined email body or customise it to fit your brand. Add dynamic data by using the variables provided.
     * @type {string}
     * @memberof ContentDto
     */
    body: string;
    /**
     * Add your own logo to the top of the email or use our pre-defined header image. If you use your own header image please ensure it is maximum 1370 x 700, or has a 2:1 aspect ratio.
     * @type {string}
     * @memberof ContentDto
     */
    headerImage: string;
    /**
     * Boolean flag indicates customized body.
     * @type {boolean}
     * @memberof ContentDto
     */
    isBodyCustom: boolean;
    /**
     * Hide our email footer explaining the benefits of Greenspark.
     * @type {boolean}
     * @memberof ContentDto
     */
    isFooterHidden: boolean;
    /**
     * Boolean flag indicates customized hidden footer setting.
     * @type {boolean}
     * @memberof ContentDto
     */
    isFooterHiddenCustom: boolean;
    /**
     * Boolean flag indicates customized header image.
     * @type {boolean}
     * @memberof ContentDto
     */
    isHeaderImageCustom: boolean;
    /**
     * Hide your total impact so far within your emails.
     * @type {boolean}
     * @memberof ContentDto
     */
    isTotalImpactHidden: boolean;
    /**
     * Boolean flag indicates customized hidden total impact setting.
     * @type {boolean}
     * @memberof ContentDto
     */
    isTotalImpactHiddenCustom: boolean;
}
