/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ScheduleDto
 */
export interface ScheduleDto {
    /**
     * The end date of the scheduled email sending.
     * @type {Date}
     * @memberof ScheduleDto
     */
    endDate: Date;
    /**
     * Boolean flag indicates customized schedule end date.
     * @type {boolean}
     * @memberof ScheduleDto
     */
    isEndDateCustom: boolean;
    /**
     * The start date of the scheduled email sending.
     * @type {Date}
     * @memberof ScheduleDto
     */
    startDate: Date;
}
