/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NotificationTemplateRequestDto } from './notification-template-request-dto';
/**
 * 
 * @export
 * @interface TestNotificationTemplateRequestDto
 */
export interface TestNotificationTemplateRequestDto {
    /**
     * Test recipient email address.
     * @type {string}
     * @memberof TestNotificationTemplateRequestDto
     */
    customerEmail: string;
    /**
     * Notification template to test.
     * @type {NotificationTemplateRequestDto}
     * @memberof TestNotificationTemplateRequestDto
     */
    notificationTemplate: NotificationTemplateRequestDto;
}
