/* tslint:disable */
/* eslint-disable */
/**
 * Estimations
 * Here you can find documentation and examples for Greenspark Estimations API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Metadata } from './metadata';
/**
 * 
 * @export
 * @interface EstimationsByCategoryTypeRequestBody
 */
export interface EstimationsByCategoryTypeRequestBody {
    /**
     * Price of purchase.
     * @type {number}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    price: number;
    /**
     * Type of category.
     * @type {string}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    categoryType: EstimationsByCategoryTypeRequestBodyCategoryTypeEnum;
    /**
     * The name of the category used to calculate the co2 emission. We support all [plaid categories](https://plaid.com/docs/api/products/transactions/#categoriesget) and the new categorisation for [personal_finance_category](https://plaid.com/docs/api/products/transactions/#transactions-recurring-get-request-options-include-personal-finance-category), as well as True Layer [categories](https://docs.truelayer.com/docs/transaction-types).
     * @type {Array<string>}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    categoryValue: Array<string>;
    /**
     * ISO Currency Code of Purchase.
     * @type {string}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    currencyISO: string;
    /**
     * Indicates the specific country that should be used for the CO2 emissions factors.
     * @type {string}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    geo?: EstimationsByCategoryTypeRequestBodyGeoEnum;
    /**
     * Indicates whether the API should use emissions factors for people or businesses (Either: \"PERSONAL\"(default), \"BUSINESS\")
     * @type {string}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    userType?: EstimationsByCategoryTypeRequestBodyUserTypeEnum;
    /**
     * In the metadata array you can store up to 10 key-value pairs. You can use them to associate arbitrary data with your estimation.
     * @type {Array<Metadata>}
     * @memberof EstimationsByCategoryTypeRequestBody
     */
    metadata?: Array<Metadata>;
}

/**
    * @export
    * @enum {string}
    */
export enum EstimationsByCategoryTypeRequestBodyCategoryTypeEnum {
    TrueLayer = 'true_layer',
    Plaid = 'plaid'
}
/**
    * @export
    * @enum {string}
    */
export enum EstimationsByCategoryTypeRequestBodyGeoEnum {
    USA = 'USA',
    EUUK = 'EU/UK',
    GB = 'GB',
    BG = 'BG',
    AT = 'AT',
    AU = 'AU',
    BE = 'BE',
    BR = 'BR',
    CA = 'CA',
    CH = 'CH',
    CN = 'CN',
    CZ = 'CZ',
    DE = 'DE',
    DK = 'DK',
    ES = 'ES',
    FR = 'FR',
    GR = 'GR',
    HR = 'HR',
    HU = 'HU',
    IT = 'IT',
    JP = 'JP',
    KR = 'KR',
    LT = 'LT',
    LV = 'LV',
    MX = 'MX',
    NL = 'NL',
    NO = 'NO',
    PL = 'PL',
    PT = 'PT',
    RU = 'RU',
    SK = 'SK',
    TW = 'TW',
    WA = 'WA',
    WE = 'WE',
    WF = 'WF',
    WL = 'WL',
    WM = 'WM',
    EE = 'EE',
    ID = 'ID',
    IE = 'IE',
    MT = 'MT',
    SE = 'SE',
    SI = 'SI',
    ZA = 'ZA'
}
/**
    * @export
    * @enum {string}
    */
export enum EstimationsByCategoryTypeRequestBodyUserTypeEnum {
    PERSONAL = 'PERSONAL',
    BUSINESS = 'BUSINESS'
}

