/* tslint:disable */
/* eslint-disable */
/**
 * Estimations
 * Here you can find documentation and examples for Greenspark Estimations API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EstimationsByCategoryType
 */
export interface EstimationsByCategoryType {
    /**
     * Price of purchase.
     * @type {number}
     * @memberof EstimationsByCategoryType
     */
    price: number;
    /**
     * Type of category.
     * @type {string}
     * @memberof EstimationsByCategoryType
     */
    categoryType: EstimationsByCategoryTypeCategoryTypeEnum;
    /**
     * The name of the category used to calculate the co2 emission. We support all [plaid categories](https://plaid.com/docs/api/products/transactions/#categoriesget) and the new categorisation for [personal_finance_category](https://plaid.com/docs/api/products/transactions/#transactions-recurring-get-request-options-include-personal-finance-category), as well as True Layer [categories](https://docs.truelayer.com/docs/transaction-types).
     * @type {Array<string>}
     * @memberof EstimationsByCategoryType
     */
    categoryValue: Array<string>;
    /**
     * ISO Currency Code of Purchase.
     * @type {string}
     * @memberof EstimationsByCategoryType
     */
    currencyISO: string;
}

/**
    * @export
    * @enum {string}
    */
export enum EstimationsByCategoryTypeCategoryTypeEnum {
    TrueLayer = 'true_layer',
    Plaid = 'plaid'
}

