/* tslint:disable */
/* eslint-disable */
/**
 * Estimations
 * Here you can find documentation and examples for Greenspark Estimations API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Metadata
 */
export interface Metadata {
    /**
     * Minimum 1, maximum 40 characters.
     * @type {string}
     * @memberof Metadata
     */
    key: string;
    /**
     * Minimum 1, maximum 80 characters.
     * @type {string}
     * @memberof Metadata
     */
    value: string;
}
