/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BatchImpactPurchaseResponse } from './batch-impact-purchase-response';
/**
 * 
 * @export
 * @interface BatchImpactPurchaseResponses
 */
export interface BatchImpactPurchaseResponses {
    /**
     * The responses array contains the results of the batch impact purchases.
     * @type {Array<BatchImpactPurchaseResponse>}
     * @memberof BatchImpactPurchaseResponses
     */
    responses: Array<BatchImpactPurchaseResponse>;
}
