/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateImpactBatchRequest } from './create-impact-batch-request';
/**
 * 
 * @export
 * @interface CreateImpactBatchRequestBody
 */
export interface CreateImpactBatchRequestBody {
    /**
     * The requests array defines the list of impacts you would like to create.
     * @type {Array<CreateImpactBatchRequest>}
     * @memberof CreateImpactBatchRequestBody
     */
    requests: Array<CreateImpactBatchRequest>;
}
