/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EvidenceImage
 */
export interface EvidenceImage {
    /**
     * The altitude when the evidence image was taken.
     * @type {number}
     * @memberof EvidenceImage
     */
    alt?: number;
    /**
     * The longitude when the evidence image was taken.
     * @type {number}
     * @memberof EvidenceImage
     */
    lng?: number;
    /**
     * The latitude when the evidence image was taken.
     * @type {number}
     * @memberof EvidenceImage
     */
    lat?: number;
    /**
     * The url of the evidence image.
     * @type {number}
     * @memberof EvidenceImage
     */
    url: number;
}
