/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EvidenceImageResponse
 */
export interface EvidenceImageResponse {
    /**
     * Altitude
     * @type {number}
     * @memberof EvidenceImageResponse
     */
    altitude: number;
    /**
     * Longitude
     * @type {number}
     * @memberof EvidenceImageResponse
     */
    longitude: number;
    /**
     * Latitude
     * @type {number}
     * @memberof EvidenceImageResponse
     */
    latitude: number;
    /**
     * Public URL of the image.
     * @type {string}
     * @memberof EvidenceImageResponse
     */
    url: string;
    /**
     * Optional preview URL of the image.
     * @type {string}
     * @memberof EvidenceImageResponse
     */
    previewUrl?: string;
    /**
     * Alternate text for the image.
     * @type {string}
     * @memberof EvidenceImageResponse
     */
    alt?: string;
}
