/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EvidenceGeoJSON
 */
export interface EvidenceGeoJSON {
    /**
     * The geometry of the evidence, type of FeatureCollection. Could be a planting route, planting are, etc.
     * @type {any}
     * @memberof EvidenceGeoJSON
     */
    geoJSON: any;
}
