/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EvidenceVideoResponse
 */
export interface EvidenceVideoResponse {
    /**
     * Altitude
     * @type {number}
     * @memberof EvidenceVideoResponse
     */
    altitude: number;
    /**
     * Longitude
     * @type {number}
     * @memberof EvidenceVideoResponse
     */
    longitude: number;
    /**
     * Latitude
     * @type {number}
     * @memberof EvidenceVideoResponse
     */
    latitude: number;
    /**
     * Public URL of the video.
     * @type {string}
     * @memberof EvidenceVideoResponse
     */
    url: string;
    /**
     * Optional preview URL of the video.
     * @type {string}
     * @memberof EvidenceVideoResponse
     */
    previewUrl?: string;
    /**
     * Alternate text for the video.
     * @type {string}
     * @memberof EvidenceVideoResponse
     */
    alt?: string;
}
