/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EvidenceImageResponse } from './evidence-image-response';
import { EvidenceVideoResponse } from './evidence-video-response';
import { FeatureCollectionDto } from './feature-collection-dto';
/**
 * 
 * @export
 * @interface ExternalReportResponse
 */
export interface ExternalReportResponse {
    /**
     * External report id.
     * @type {string}
     * @memberof ExternalReportResponse
     */
    externalId: string;
    /**
     * External report title.
     * @type {string}
     * @memberof ExternalReportResponse
     */
    title?: string | null;
    /**
     * ISO date when this report was reported.
     * @type {string}
     * @memberof ExternalReportResponse
     */
    reportedAt?: string | null;
    /**
     * Field update id associated with this report.
     * @type {number}
     * @memberof ExternalReportResponse
     */
    fieldUpdateId: number;
    /**
     * Images attached to this report.
     * @type {Array<EvidenceImageResponse>}
     * @memberof ExternalReportResponse
     */
    images?: Array<EvidenceImageResponse>;
    /**
     * GeoJSON objects attached to this report.
     * @type {Array<FeatureCollectionDto>}
     * @memberof ExternalReportResponse
     */
    geoJSON?: Array<FeatureCollectionDto>;
    /**
     * Videos attached to this report.
     * @type {Array<EvidenceVideoResponse>}
     * @memberof ExternalReportResponse
     */
    videos?: Array<EvidenceVideoResponse>;
}
