/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ImpactPurchaseDetail
 */
export interface ImpactPurchaseDetail {
    /**
     * Type of the impact you purchased.
     * @type {string}
     * @memberof ImpactPurchaseDetail
     */
    type: ImpactPurchaseDetailTypeEnum;
    /**
     * Amount of the impact you purchased.
     * @type {number}
     * @memberof ImpactPurchaseDetail
     */
    amount: number;
    /**
     * The value which has been spent on your chosen impacts and will therefore be billed.
     * @type {number}
     * @memberof ImpactPurchaseDetail
     */
    spentValue: number;
    /**
     * Any value which is not spent. This is due to the difference between the value you have chosen to spend and the actual price of the impacts. You will not be billed for this. 
     * @type {number}
     * @memberof ImpactPurchaseDetail
     */
    unspentValue: number;
    /**
     * The id of the project.
     * @type {string}
     * @memberof ImpactPurchaseDetail
     */
    projectId: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ImpactPurchaseDetailTypeEnum {
    Trees = 'trees',
    Carbon = 'carbon',
    Plastic = 'plastic',
    Kelp = 'kelp'
}

