/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlantingSessionBlockchainResponse
 */
export interface PlantingSessionBlockchainResponse {
    /**
     * Blockchain transaction id.
     * @type {string}
     * @memberof PlantingSessionBlockchainResponse
     */
    transactionId?: string | null;
    /**
     * Arweave URL, if available.
     * @type {string}
     * @memberof PlantingSessionBlockchainResponse
     */
    arweaveUrl?: string | null;
    /**
     * IPFS URL, if available.
     * @type {string}
     * @memberof PlantingSessionBlockchainResponse
     */
    ipfsUrl?: string | null;
}
