/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlantingSpeciesResponse
 */
export interface PlantingSpeciesResponse {
    /**
     * Species common name.
     * @type {string}
     * @memberof PlantingSpeciesResponse
     */
    name: string;
    /**
     * Amount planted for this species.
     * @type {number}
     * @memberof PlantingSpeciesResponse
     */
    amountPlanted: number;
}
