/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EvidenceImageResponse } from './evidence-image-response';
import { EvidenceVideoResponse } from './evidence-video-response';
import { FeatureCollectionDto } from './feature-collection-dto';
import { PlantingSpeciesResponse } from './planting-species-response';
/**
 * 
 * @export
 * @interface PlantingDetailsResponse
 */
export interface PlantingDetailsResponse {
    /**
     * ISO date when the planting happened.
     * @type {string}
     * @memberof PlantingDetailsResponse
     */
    datePlanted?: string | null;
    /**
     * Planting start time (ISO-8601).
     * @type {string}
     * @memberof PlantingDetailsResponse
     */
    startTime?: string | null;
    /**
     * Planting end time (ISO-8601).
     * @type {string}
     * @memberof PlantingDetailsResponse
     */
    endTime?: string | null;
    /**
     * Name of the site forester.
     * @type {string}
     * @memberof PlantingDetailsResponse
     */
    siteForester?: string | null;
    /**
     * Number of planters.
     * @type {number}
     * @memberof PlantingDetailsResponse
     */
    numberOfPlanters?: number | null;
    /**
     * Notes captured during planting.
     * @type {string}
     * @memberof PlantingDetailsResponse
     */
    notes?: string | null;
    /**
     * Total amount planted during this session.
     * @type {number}
     * @memberof PlantingDetailsResponse
     */
    amountPlanted?: number | null;
    /**
     * Images attached to planting details.
     * @type {Array<EvidenceImageResponse>}
     * @memberof PlantingDetailsResponse
     */
    images?: Array<EvidenceImageResponse>;
    /**
     * GeoJSON objects attached to planting details.
     * @type {Array<FeatureCollectionDto>}
     * @memberof PlantingDetailsResponse
     */
    geoJSON?: Array<FeatureCollectionDto>;
    /**
     * Videos attached to planting details.
     * @type {Array<EvidenceVideoResponse>}
     * @memberof PlantingDetailsResponse
     */
    videos?: Array<EvidenceVideoResponse>;
    /**
     * Species breakdown for this planting session.
     * @type {Array<PlantingSpeciesResponse>}
     * @memberof PlantingDetailsResponse
     */
    species?: Array<PlantingSpeciesResponse>;
}
