/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExternalReportResponse } from './external-report-response';
import { PlantingDetailsResponse } from './planting-details-response';
import { PlantingSessionBlockchainResponse } from './planting-session-blockchain-response';
import { SiteAssessmentResponse } from './site-assessment-response';
import { SurvivabilityStats } from './survivability-stats';
import { VeritreeSubsiteResponse } from './veritree-subsite-response';
/**
 * 
 * @export
 * @interface PlantingSessionResponse
 */
export interface PlantingSessionResponse {
    /**
     * Unique identifier of the field update.
     * @type {number}
     * @memberof PlantingSessionResponse
     */
    fieldUpdateId: number;
    /**
     * Present only when the planting session is related to the authenticated account.
     * @type {string}
     * @memberof PlantingSessionResponse
     */
    accountId?: string;
    /**
     * Site assessment details.
     * @type {SiteAssessmentResponse}
     * @memberof PlantingSessionResponse
     */
    siteAssessment: SiteAssessmentResponse;
    /**
     * Planting details.
     * @type {PlantingDetailsResponse}
     * @memberof PlantingSessionResponse
     */
    planting: PlantingDetailsResponse;
    /**
     * Blockchain references for this planting session.
     * @type {PlantingSessionBlockchainResponse}
     * @memberof PlantingSessionResponse
     */
    blockchain: PlantingSessionBlockchainResponse;
    /**
     * Optional survivability stats.
     * @type {SurvivabilityStats}
     * @memberof PlantingSessionResponse
     */
    survivabilityStats?: SurvivabilityStats | null;
    /**
     * External reports attached to this session.
     * @type {Array<ExternalReportResponse>}
     * @memberof PlantingSessionResponse
     */
    externalReports?: Array<ExternalReportResponse>;
    /**
     * Altitude
     * @type {number}
     * @memberof PlantingSessionResponse
     */
    altitude: number;
    /**
     * Longitude
     * @type {number}
     * @memberof PlantingSessionResponse
     */
    longitude: number;
    /**
     * Latitude
     * @type {number}
     * @memberof PlantingSessionResponse
     */
    latitude: number;
    /**
     * Subsite associated with this session.
     * @type {VeritreeSubsiteResponse}
     * @memberof PlantingSessionResponse
     */
    site: VeritreeSubsiteResponse;
    /**
     * Discriminator type for evidence unions.
     * @type {string}
     * @memberof PlantingSessionResponse
     */
    type: string;
}
