/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeatureCollectionDto } from './feature-collection-dto';
/**
 * 
 * @export
 * @interface PlasticCollectionResponse
 */
export interface PlasticCollectionResponse {
    /**
     * Present only when the collection is related to the authenticated account.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    accountId?: string;
    /**
     * The name of the collector who collected the plastic waste.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    collectorName: string;
    /**
     * The name of the buyer who buys the plastic waste from the collector.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    buyerName: string;
    /**
     * The type of plastic material collected.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    materialType: string;
    /**
     * The weight of the collected plastic waste.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    weight: string;
    /**
     * Number of plastic bottles rescues, computed from weight.
     * @type {number}
     * @memberof PlasticCollectionResponse
     */
    numberOfPlasticBottlesRescued: number;
    /**
     * The geometry of the plastic collection.
     * @type {FeatureCollectionDto}
     * @memberof PlasticCollectionResponse
     */
    geoJSON: FeatureCollectionDto;
    /**
     * The creation time of the plastic collection (ISO-8601).
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    createdAt: string;
    /**
     * External identifier for the plastic collection.
     * @type {string}
     * @memberof PlasticCollectionResponse
     */
    externalId: string;
}
