/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EvidenceImageResponse } from './evidence-image-response';
import { EvidenceVideoResponse } from './evidence-video-response';
import { FeatureCollectionDto } from './feature-collection-dto';
/**
 * 
 * @export
 * @interface SiteAssessmentResponse
 */
export interface SiteAssessmentResponse {
    /**
     * Planting site name.
     * @type {string}
     * @memberof SiteAssessmentResponse
     */
    plantingSite?: string | null;
    /**
     * ISO timestamp when the assessment was done.
     * @type {string}
     * @memberof SiteAssessmentResponse
     */
    assessedAt?: string | null;
    /**
     * Assessor full name.
     * @type {string}
     * @memberof SiteAssessmentResponse
     */
    assessorName?: string | null;
    /**
     * Notes captured during assessment.
     * @type {string}
     * @memberof SiteAssessmentResponse
     */
    notes?: string | null;
    /**
     * Images attached to the assessment.
     * @type {Array<EvidenceImageResponse>}
     * @memberof SiteAssessmentResponse
     */
    images?: Array<EvidenceImageResponse>;
    /**
     * GeoJSON objects attached to the assessment.
     * @type {Array<FeatureCollectionDto>}
     * @memberof SiteAssessmentResponse
     */
    geoJSON?: Array<FeatureCollectionDto>;
    /**
     * Videos attached to the assessment.
     * @type {Array<EvidenceVideoResponse>}
     * @memberof SiteAssessmentResponse
     */
    videos?: Array<EvidenceVideoResponse>;
}
