/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SurvivabilityMetric } from './survivability-metric';
/**
 * 
 * @export
 * @interface SurvivabilityStats
 */
export interface SurvivabilityStats {
    /**
     * Field update id (Veritree)
     * @type {number}
     * @memberof SurvivabilityStats
     */
    fieldUpdateId: number;
    /**
     * Survivability metrics for this field update.
     * @type {Array<SurvivabilityMetric>}
     * @memberof SurvivabilityStats
     */
    metrics: Array<SurvivabilityMetric>;
}
