/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SurvivabilityMetric
 */
export interface SurvivabilityMetric {
    /**
     * Metric name.
     * @type {string}
     * @memberof SurvivabilityMetric
     */
    name: string;
    /**
     * Metric value.
     * @type {number}
     * @memberof SurvivabilityMetric
     */
    value: number;
    /**
     * Unit for the metric value.
     * @type {string}
     * @memberof SurvivabilityMetric
     */
    unit: string;
    /**
     * ISO timestamp when the metric was last updated.
     * @type {string}
     * @memberof SurvivabilityMetric
     */
    updatedAt: string;
    /**
     * Metric type/category.
     * @type {string}
     * @memberof SurvivabilityMetric
     */
    type: string;
}
