/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EvidenceGeoJSON } from './evidence-geo-json';
import { EvidenceImage } from './evidence-image';
import { ModelString } from './model-string';
import { Number } from './number';
/**
 * 
 * @export
 * @interface TransactionPurchaseMetadata
 */
export interface TransactionPurchaseMetadata {
    /**
     * The key of the evidence.
     * @type {string}
     * @memberof TransactionPurchaseMetadata
     */
    key: string;
    /**
     * The value of the evidence.
     * @type {EvidenceImage | EvidenceGeoJSON | ModelString | Number}
     * @memberof TransactionPurchaseMetadata
     */
    value: EvidenceImage | EvidenceGeoJSON | ModelString | Number;
    /**
     * The type of the evidence.
     * @type {string}
     * @memberof TransactionPurchaseMetadata
     */
    type: TransactionPurchaseMetadataTypeEnum;
    /**
     * The creation time of the evidence.
     * @type {string}
     * @memberof TransactionPurchaseMetadata
     */
    createdAt: string;
}

/**
    * @export
    * @enum {string}
    */
export enum TransactionPurchaseMetadataTypeEnum {
    EvidenceImage = 'EvidenceImage',
    EvidenceGeoJSON = 'EvidenceGeoJSON',
    String = 'String',
    Number = 'Number'
}

