/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionPurchaseMetadata } from './transaction-purchase-metadata';
/**
 * 
 * @export
 * @interface TransactionPurchase
 */
export interface TransactionPurchase {
    /**
     * The id of the purchase.
     * @type {string}
     * @memberof TransactionPurchase
     */
    id: string;
    /**
     * The type of the purchase.
     * @type {string}
     * @memberof TransactionPurchase
     */
    type: TransactionPurchaseTypeEnum;
    /**
     * The impact amount of the purchase.
     * @type {number}
     * @memberof TransactionPurchase
     */
    amount: number;
    /**
     * The project id of the purchase.
     * @type {string}
     * @memberof TransactionPurchase
     */
    projectId: string;
    /**
     * The receipt url of the purchase.
     * @type {string}
     * @memberof TransactionPurchase
     */
    receiptUrl: string;
    /**
     * The provider of the impacts.
     * @type {string}
     * @memberof TransactionPurchase
     */
    provider: string;
    /**
     * The start of the period the purchase made for.
     * @type {string}
     * @memberof TransactionPurchase
     */
    periodStartDate: string;
    /**
     * The end of the period the purchase made for.
     * @type {string}
     * @memberof TransactionPurchase
     */
    periodEndDate: string;
    /**
     * The evidences of a purchase.
     * @type {TransactionPurchaseMetadata}
     * @memberof TransactionPurchase
     */
    evidences: TransactionPurchaseMetadata;
}

/**
    * @export
    * @enum {string}
    */
export enum TransactionPurchaseTypeEnum {
    Trees = 'trees',
    Carbon = 'carbon',
    Plastic = 'plastic',
    Kelp = 'kelp',
    Water = 'water'
}

