/* tslint:disable */
/* eslint-disable */
/**
 * Impact
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface VeritreeSubsiteResponse
 */
export interface VeritreeSubsiteResponse {
    /**
     * Veritree subsite id.
     * @type {number}
     * @memberof VeritreeSubsiteResponse
     */
    id: number;
    /**
     * Latitude
     * @type {number}
     * @memberof VeritreeSubsiteResponse
     */
    latitude: number;
    /**
     * Longitude
     * @type {number}
     * @memberof VeritreeSubsiteResponse
     */
    longitude: number;
    /**
     * Geofence for this subsite as a GeoJSON MultiPolygon.
     * @type {any}
     * @memberof VeritreeSubsiteResponse
     */
    geofences: any;
}
