/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ScheduleRequestBody struct {
	// The start date of the scheduled email sending.
	StartDate time.Time `json:"startDate"`
	// The end date of the scheduled email sending.
	EndDate time.Time `json:"endDate"`
}
