/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DnsDto struct {
	// Record that must be added to your domain.
	MailCname *AllOfDnsDtoMailCname `json:"mailCname"`
	// Record that must be added to your domain.
	Dkim1 *AllOfDnsDtoDkim1 `json:"dkim1"`
	// Record that must be added to your domain.
	Dkim2 *AllOfDnsDtoDkim2 `json:"dkim2"`
}
