/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Notification template to test.
type AllOfTestNotificationTemplateRequestDtoNotificationTemplate struct {
	// Start sending this template to your customers.
	IsActive bool `json:"isActive"`
	Type_ *TypeRequestBody `json:"type"`
	Settings *SettingsRequestBody `json:"settings"`
	Content *ContentRequestBody `json:"content"`
}
