/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SettingsRequestBody struct {
	// The email address used for sending emails.
	From *AllOfSettingsRequestBodyFrom `json:"from"`
	// This is the name display for the specified sender email address.
	Alias string `json:"alias"`
	// Your subject line is one of the first things that your customers read and is a key driver in successful open rates.
	Subject string `json:"subject"`
	// The preheader is the text following the subject line when an email is previewed.
	Preheader string `json:"preheader"`
	// You can choose to send your template continuously starting today or only during a specific date range.
	Schedule *AllOfSettingsRequestBodySchedule `json:"schedule"`
}
