/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Record that must be added to your domain.
type AllOfDnsDtoDkim1 struct {
	// The indicator of the DNS record validity.
	Valid bool `json:"valid"`
	// The type of the record that must be added to your domain.
	Type_ string `json:"type"`
	// The type of the record that must be added to your domain.
	Host string `json:"host"`
	// The value of the record that must be added to your domain.
	Data string `json:"data"`
}
