/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This object contains the DNS records that must be added to your domain.
type AllOfCustomDomainDtoDns struct {
	// Record that must be added to your domain.
	MailCname *Object `json:"mailCname"`
	// Record that must be added to your domain.
	Dkim1 *Object `json:"dkim1"`
	// Record that must be added to your domain.
	Dkim2 *Object `json:"dkim2"`
}
