/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// You can choose to send your template continuously starting today or only during a specific date range.
type AllOfSettingsDtoSchedule struct {
	// The end date of the scheduled email sending.
	EndDate time.Time `json:"endDate"`
	// Boolean flag indicates customized schedule end date.
	IsEndDateCustom bool `json:"isEndDateCustom"`
	// The start date of the scheduled email sending.
	StartDate time.Time `json:"startDate"`
}
