/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The email address used for sending emails.
type AllOfSettingsDtoFrom struct {
	// The domain name used for sending emails based on this template.
	Domain string `json:"domain"`
	// The name part of the email address.
	Name string `json:"name"`
}
