/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TypeRequestBody struct {
	// Name of the template
	Name string `json:"name"`
	// The type of the template.
	Template string `json:"template"`
	// Choose the impact action which triggers your email to be sent out.
	Trigger []string `json:"trigger"`
	// Choose when your nudge email is sent out after a customer completes an impact action.
	Schedule []int32 `json:"schedule"`
}
