/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ContentDto struct {
	// Use our pre-defined email body or customise it to fit your brand. Add dynamic data by using the variables provided.
	Body string `json:"body"`
	// Add your own logo to the top of the email or use our pre-defined header image. If you use your own header image please ensure it is maximum 1370 x 700, or has a 2:1 aspect ratio.
	HeaderImage string `json:"headerImage"`
	// Boolean flag indicates customized body.
	IsBodyCustom bool `json:"isBodyCustom"`
	// Hide our email footer explaining the benefits of Greenspark.
	IsFooterHidden bool `json:"isFooterHidden"`
	// Boolean flag indicates customized hidden footer setting.
	IsFooterHiddenCustom bool `json:"isFooterHiddenCustom"`
	// Boolean flag indicates customized header image.
	IsHeaderImageCustom bool `json:"isHeaderImageCustom"`
	// Hide your total impact so far within your emails.
	IsTotalImpactHidden bool `json:"isTotalImpactHidden"`
	// Boolean flag indicates customized hidden total impact setting.
	IsTotalImpactHiddenCustom bool `json:"isTotalImpactHiddenCustom"`
}
