/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TypeDto struct {
	// Boolean flag indicates customized schedule.
	IsScheduleCustom bool `json:"isScheduleCustom"`
	// Boolean flag indicates customized trigger.
	IsTriggerCustom bool `json:"isTriggerCustom"`
	// Name of the template
	Name string `json:"name"`
	// Choose when your nudge email is sent out after a customer completes an impact action.
	Schedule []string `json:"schedule"`
	// The type of the template.
	Template *interface{} `json:"template"`
	// Choose the impact action which triggers your email to be sent out.
	Trigger []string `json:"trigger"`
}
