/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NotificationTemplateResponseDto struct {
	// The id of the template.
	Id string `json:"id"`
	// Start sending this template to your customers.
	IsActive bool `json:"isActive"`
	// Boolean flag indicates customized template.
	IsCustom bool `json:"isCustom"`
	Type_ *TypeDto `json:"type"`
	Settings *SettingsDto `json:"settings"`
	Content *ContentDto `json:"content"`
}
