/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SettingsDto struct {
	// This is the name display for the specified sender email address.
	Alias string `json:"alias"`
	// The email address used for sending emails.
	From *AllOfSettingsDtoFrom `json:"from"`
	// Boolean flag indicates customized alias.
	IsAliasCustom bool `json:"isAliasCustom"`
	// Boolean flag indicates customized sender email address.
	IsFromCustom bool `json:"isFromCustom"`
	// Boolean flag indicates customized preheader.
	IsPreheaderCustom bool `json:"isPreheaderCustom"`
	// Boolean flag indicates customized subject.
	IsSubjectCustom bool `json:"isSubjectCustom"`
	// The preheader is the text following the subject line when an email is previewed.
	Preheader string `json:"preheader"`
	// You can choose to send your template continuously starting today or only during a specific date range.
	Schedule *AllOfSettingsDtoSchedule `json:"schedule"`
	// Your subject line is one of the first things that your customers read and is a key driver in successful open rates.
	Subject string `json:"subject"`
}
