/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomDomainDto struct {
	// The id of the custom domain object.
	Id string `json:"id"`
	// The domain name.
	Domain string `json:"domain"`
	// This object contains the DNS records that must be added to your domain.
	Dns *AllOfCustomDomainDtoDns `json:"dns"`
	// The indicator of the DNS records validity.
	Valid bool `json:"valid"`
}
