/*
 * Email
 *
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TestNotificationTemplateRequestDto struct {
	// Test recipient email address.
	CustomerEmail string `json:"customerEmail"`
	// Notification template to test.
	NotificationTemplate *AllOfTestNotificationTemplateRequestDtoNotificationTemplate `json:"notificationTemplate"`
}
