/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DnsDto } from './dns-dto';
/**
 * 
 * @export
 * @interface CustomDomainDto
 */
export interface CustomDomainDto {
    /**
     * The id of the custom domain object.
     * @type {string}
     * @memberof CustomDomainDto
     */
    id: string;
    /**
     * The domain name.
     * @type {string}
     * @memberof CustomDomainDto
     */
    domain: string;
    /**
     * This object contains the DNS records that must be added to your domain.
     * @type {DnsDto}
     * @memberof CustomDomainDto
     */
    dns: DnsDto;
    /**
     * The indicator of the DNS records validity.
     * @type {boolean}
     * @memberof CustomDomainDto
     */
    valid: boolean;
}
