/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CustomDomainRequestBody
 */
export interface CustomDomainRequestBody {
    /**
     * The domain name.
     * @type {string}
     * @memberof CustomDomainRequestBody
     */
    domain: string;
}
