/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EmailDto
 */
export interface EmailDto {
    /**
     * The domain name used for sending emails based on this template.
     * @type {string}
     * @memberof EmailDto
     */
    domain: string;
    /**
     * The name part of the email address.
     * @type {string}
     * @memberof EmailDto
     */
    name: string;
}
