/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentDto } from './content-dto';
import { SettingsDto } from './settings-dto';
import { TypeDto } from './type-dto';
/**
 * 
 * @export
 * @interface NotificationTemplateResponseDto
 */
export interface NotificationTemplateResponseDto {
    /**
     * The id of the template.
     * @type {string}
     * @memberof NotificationTemplateResponseDto
     */
    id: string;
    /**
     * Start sending this template to your customers.
     * @type {boolean}
     * @memberof NotificationTemplateResponseDto
     */
    isActive: boolean;
    /**
     * Boolean flag indicates customized template.
     * @type {boolean}
     * @memberof NotificationTemplateResponseDto
     */
    isCustom: boolean;
    /**
     * 
     * @type {TypeDto}
     * @memberof NotificationTemplateResponseDto
     */
    type: TypeDto;
    /**
     * 
     * @type {SettingsDto}
     * @memberof NotificationTemplateResponseDto
     */
    settings: SettingsDto;
    /**
     * 
     * @type {ContentDto}
     * @memberof NotificationTemplateResponseDto
     */
    content: ContentDto;
}
