/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContentRequestBody } from './content-request-body';
import { SettingsRequestBody } from './settings-request-body';
import { TypeRequestBody } from './type-request-body';
/**
 * 
 * @export
 * @interface NotificationTemplateRequestDto
 */
export interface NotificationTemplateRequestDto {
    /**
     * Start sending this template to your customers.
     * @type {boolean}
     * @memberof NotificationTemplateRequestDto
     */
    isActive: boolean;
    /**
     * 
     * @type {TypeRequestBody}
     * @memberof NotificationTemplateRequestDto
     */
    type: TypeRequestBody;
    /**
     * 
     * @type {SettingsRequestBody}
     * @memberof NotificationTemplateRequestDto
     */
    settings: SettingsRequestBody;
    /**
     * 
     * @type {ContentRequestBody}
     * @memberof NotificationTemplateRequestDto
     */
    content: ContentRequestBody;
}
