/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailDto } from './email-dto';
import { ScheduleDto } from './schedule-dto';
/**
 * 
 * @export
 * @interface SettingsDto
 */
export interface SettingsDto {
    /**
     * This is the name display for the specified sender email address.
     * @type {string}
     * @memberof SettingsDto
     */
    alias: string;
    /**
     * The email address used for sending emails.
     * @type {EmailDto}
     * @memberof SettingsDto
     */
    from: EmailDto;
    /**
     * Boolean flag indicates customized alias.
     * @type {boolean}
     * @memberof SettingsDto
     */
    isAliasCustom: boolean;
    /**
     * Boolean flag indicates customized sender email address.
     * @type {boolean}
     * @memberof SettingsDto
     */
    isFromCustom: boolean;
    /**
     * Boolean flag indicates customized preheader.
     * @type {boolean}
     * @memberof SettingsDto
     */
    isPreheaderCustom: boolean;
    /**
     * Boolean flag indicates customized subject.
     * @type {boolean}
     * @memberof SettingsDto
     */
    isSubjectCustom: boolean;
    /**
     * The preheader is the text following the subject line when an email is previewed.
     * @type {string}
     * @memberof SettingsDto
     */
    preheader: string;
    /**
     * You can choose to send your template continuously starting at the selected start date or only during a specific date range.
     * @type {ScheduleDto}
     * @memberof SettingsDto
     */
    schedule: ScheduleDto;
    /**
     * Your subject line is one of the first things that your customers read and is a key driver in successful open rates.
     * @type {string}
     * @memberof SettingsDto
     */
    subject: string;
}
