/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmailRequestBody } from './email-request-body';
import { ScheduleRequestBody } from './schedule-request-body';
/**
 * 
 * @export
 * @interface SettingsRequestBody
 */
export interface SettingsRequestBody {
    /**
     * The email address used for sending emails.
     * @type {EmailRequestBody}
     * @memberof SettingsRequestBody
     */
    from: EmailRequestBody;
    /**
     * This is the name display for the specified sender email address.
     * @type {string}
     * @memberof SettingsRequestBody
     */
    alias: string;
    /**
     * Your subject line is one of the first things that your customers read and is a key driver in successful open rates.
     * @type {string}
     * @memberof SettingsRequestBody
     */
    subject: string;
    /**
     * The preheader is the text following the subject line when an email is previewed.
     * @type {string}
     * @memberof SettingsRequestBody
     */
    preheader: string;
    /**
     * You can choose to send your template continuously starting at the selected start date or only during a specific date range.
     * @type {ScheduleRequestBody}
     * @memberof SettingsRequestBody
     */
    schedule: ScheduleRequestBody;
}
