/* tslint:disable */
/* eslint-disable */
/**
 * Email
 * Here you can find documentation and examples for Greenspark Impact API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TypeDto
 */
export interface TypeDto {
    /**
     * Boolean flag indicates customized schedule.
     * @type {boolean}
     * @memberof TypeDto
     */
    isScheduleCustom: boolean;
    /**
     * Boolean flag indicates customized trigger.
     * @type {boolean}
     * @memberof TypeDto
     */
    isTriggerCustom: boolean;
    /**
     * Name of the template
     * @type {string}
     * @memberof TypeDto
     */
    name: string;
    /**
     * Sets how many days after an impact creation a signup nudging email is sent out to your customer.
     * @type {Array<string>}
     * @memberof TypeDto
     */
    schedule: Array<string>;
    /**
     * The type of the template.
     * @type {any}
     * @memberof TypeDto
     */
    template: any;
    /**
     * Choose the impact action which triggers your email to be sent out.
     * @type {Array<string>}
     * @memberof TypeDto
     */
    trigger: Array<string>;
}
