/* tslint:disable */
/* eslint-disable */
/**
 * Projects
 * Here you can find documentation and examples for Greenspark Projects API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeatureDto } from './feature-dto';
/**
 * 
 * @export
 * @interface FeatureCollectionDto
 */
export interface FeatureCollectionDto {
    /**
     * A collection of feature objects. https://tools.ietf.org/html/rfc7946#section-3.3
     * @type {Array<FeatureDto>}
     * @memberof FeatureCollectionDto
     */
    features: Array<FeatureDto>;
    /**
     * Specifies the type of GeoJSON object.
     * @type {string}
     * @memberof FeatureCollectionDto
     */
    type: string;
}
