/* tslint:disable */
/* eslint-disable */
/**
 * Projects
 * Here you can find documentation and examples for Greenspark Projects API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PointDto } from './point-dto';
/**
 * 
 * @export
 * @interface FeatureDto
 */
export interface FeatureDto {
    /**
     * Specifies the type of GeoJSON object.
     * @type {string}
     * @memberof FeatureDto
     */
    type: string;
    /**
     * Geometry object. https://tools.ietf.org/html/rfc7946#section-3
     * @type {PointDto}
     * @memberof FeatureDto
     */
    geometry: PointDto;
    /**
     * Properties associated with this feature.
     * @type {any}
     * @memberof FeatureDto
     */
    properties: any;
}
