/* tslint:disable */
/* eslint-disable */
/**
 * Projects
 * Here you can find documentation and examples for Greenspark Projects API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectMetadata } from './project-metadata';
/**
 * 
 * @export
 * @interface ProjectDetails
 */
export interface ProjectDetails {
    /**
     * The unique identifier of the project.
     * @type {string}
     * @memberof ProjectDetails
     */
    projectId: string;
    /**
     * Defines the category that the project falls under. It links the project to its relevant category.
     * @type {string}
     * @memberof ProjectDetails
     */
    projectCategoryId: string;
    /**
     * The name of the project.
     * @type {string}
     * @memberof ProjectDetails
     */
    name: string;
    /**
     * Detailed explanation of what the project is about. It provides more context for users who want to understand the project.
     * @type {string}
     * @memberof ProjectDetails
     */
    description: string;
    /**
     * Refers to the type of impact that the project is expected to have.
     * @type {string}
     * @memberof ProjectDetails
     */
    type: ProjectDetailsTypeEnum;
    /**
     * This is a link to a webpage where users can find more detailed information about the project.
     * @type {string}
     * @memberof ProjectDetails
     */
    registryLink?: string;
    /**
     * This is a link to the project specific Greenspark page.
     * @type {string}
     * @memberof ProjectDetails
     */
    link: string;
    /**
     * Link to an image representing the project.
     * @type {string}
     * @memberof ProjectDetails
     */
    imageUrl: string;
    /**
     * List of countries where the project is located.
     * @type {string}
     * @memberof ProjectDetails
     */
    countries: string;
    /**
     * The year when the project started.
     * @type {number}
     * @memberof ProjectDetails
     */
    vintage: number;
    /**
     * Defines how much it costs to purchase one unit of impact in the account's currency.
     * @type {number}
     * @memberof ProjectDetails
     */
    price: number;
    /**
     * Defines how many units of impact are still available for purchase through the project. If there's no limit, this would be null. For a carbon offsetting project, this would be the number of tonnes of carbon that can still be offset through the project.
     * @type {number}
     * @memberof ProjectDetails
     */
    availability?: number;
    /**
     * Defines the default project for a project category. When an impact purchase is made, the default project's impact will be purchased if the project is not specified.
     * @type {boolean}
     * @memberof ProjectDetails
     */
    _default?: boolean;
    /**
     * Defines project specific additional information.
     * @type {Array<ProjectMetadata>}
     * @memberof ProjectDetails
     */
    metadata?: Array<ProjectMetadata>;
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectDetailsTypeEnum {
    Trees = 'trees',
    Carbon = 'carbon',
    Plastic = 'plastic',
    Kelp = 'kelp'
}

