/* tslint:disable */
/* eslint-disable */
/**
 * Projects
 * Here you can find documentation and examples for Greenspark Projects API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectCategoryImage
 */
export interface ProjectCategoryImage {
    /**
     * The url of the image.
     * @type {string}
     * @memberof ProjectCategoryImage
     */
    imageUrl: string;
    /**
     * The style of the image.
     * @type {string}
     * @memberof ProjectCategoryImage
     */
    style: ProjectCategoryImageStyleEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectCategoryImageStyleEnum {
    Flat = 'flat',
    Simplified = 'simplified',
    _3d = '3d'
}

