/* tslint:disable */
/* eslint-disable */
/**
 * Projects
 * Here you can find documentation and examples for Greenspark Projects API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProjectCategoryImage } from './project-category-image';
/**
 * 
 * @export
 * @interface ProjectCategory
 */
export interface ProjectCategory {
    /**
     * The unique identifier of the project.
     * @type {string}
     * @memberof ProjectCategory
     */
    projectCategoryId: string;
    /**
     * The name of the project category.
     * @type {string}
     * @memberof ProjectCategory
     */
    name: string;
    /**
     * Detailed explanation of what the project category is about. It provides more context for users who want to understand the category.
     * @type {string}
     * @memberof ProjectCategory
     */
    description: string;
    /**
     * Images associated with the project category. They help users visualise the impact of the project category.
     * @type {Array<ProjectCategoryImage>}
     * @memberof ProjectCategory
     */
    images: Array<ProjectCategoryImage>;
    /**
     * Defines the type of environmental impact associated with projects in this category.
     * @type {string}
     * @memberof ProjectCategory
     */
    type: ProjectCategoryTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectCategoryTypeEnum {
    Trees = 'trees',
    Carbon = 'carbon',
    Plastic = 'plastic',
    Kelp = 'kelp',
    Water = 'water'
}

