/* tslint:disable */
/* eslint-disable */
/**
 * Reporting
 * Here you can find documentation and examples for Greenspark Reporting API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * The type of the spending.
     * @type {string}
     * @memberof InlineResponse200
     */
    type?: string;
    /**
     * The amount of the spending.
     * @type {number}
     * @memberof InlineResponse200
     */
    amount?: number;
}
