/* tslint:disable */
/* eslint-disable */
/**
 * Reporting
 * Here you can find documentation and examples for Greenspark Reporting API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * The name of the trigger.
     * @type {string}
     * @memberof InlineResponse2005
     */
    trigger?: string;
    /**
     * The amount of impacts.
     * @type {number}
     * @memberof InlineResponse2005
     */
    total?: number;
}
