/* tslint:disable */
/* eslint-disable */
/**
 * Reporting
 * Here you can find documentation and examples for Greenspark Reporting API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RawReportRow } from './raw-report-row';
/**
 * 
 * @export
 * @interface RawReport
 */
export interface RawReport {
    /**
     * 
     * @type {Array<RawReportRow>}
     * @memberof RawReport
     */
    rows: Array<RawReportRow>;
    /**
     * Number of rows in the report.
     * @type {number}
     * @memberof RawReport
     */
    totalRows: number;
    /**
     * Maximum number of rows per page.
     * @type {number}
     * @memberof RawReport
     */
    maxResults: number;
    /**
     * If the result set spread through multiple pages, you can fetch the next page with it. If null, it indicates that no pagination needed.
     * @type {string}
     * @memberof RawReport
     */
    cursor: string;
    /**
     * The id of your generated report. If the result set spread through multiple pages, you can refer to your report with it while pagination.
     * @type {string}
     * @memberof RawReport
     */
    reportId: string;
}
