/* tslint:disable */
/* eslint-disable */
/**
 * Reporting
 * Here you can find documentation and examples for Greenspark Reporting API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RawReportRowV2 } from './raw-report-row-v2';
/**
 * 
 * @export
 * @interface RawReportV2
 */
export interface RawReportV2 {
    /**
     * 
     * @type {Array<RawReportRowV2>}
     * @memberof RawReportV2
     */
    rows: Array<RawReportRowV2>;
    /**
     * Maximum number of rows per page.
     * @type {number}
     * @memberof RawReportV2
     */
    maxResults: number;
    /**
     * If the result set spread through multiple pages, you can fetch the next page with it. If null, it indicates that no pagination needed.
     * @type {string}
     * @memberof RawReportV2
     */
    cursor: string;
}
